-- MySQL Script generated by MySQL Workbench
-- Sat Oct 20 21:11:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotelaria_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelaria_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelaria_db` DEFAULT CHARACTER SET utf8 ;
USE `hotelaria_db` ;

-- -----------------------------------------------------
-- Table `hotelaria_db`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelaria_db`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(45) NOT NULL,
  `cliente_rg` INT NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `cliente_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelaria_db`.`tb_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelaria_db`.`tb_quarto` (
  `id_quarto` INT NOT NULL AUTO_INCREMENT,
  `quarto_apt` INT NOT NULL,
  `quarto_num_hosp` INT NULL,
  `quarto_climatizado` BINARY(0) NOT NULL,
  `quarto_diaria` INT NOT NULL,
  PRIMARY KEY (`id_quarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelaria_db`.`tb_frigobar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelaria_db`.`tb_frigobar` (
  `id_frigobar` INT NOT NULL AUTO_INCREMENT,
  `frigobar_qtd_refrigerante` INT NULL,
  `frigobar_qtd_cerveja` INT NULL,
  `frigobar_qtd_vodka` INT NULL,
  PRIMARY KEY (`id_frigobar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelaria_db`.`tb_consumo_frigobar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelaria_db`.`tb_consumo_frigobar` (
  `id_consumo_frigobar` INT NOT NULL AUTO_INCREMENT,
  `id_quarto_fk` INT NOT NULL,
  `id_frigobar_fk` INT NOT NULL,
  `consumo_qtd_refrigerante` INT NULL,
  `consumo_qtd_cerveja` INT NULL,
  `consumo_qtd_vodka` INT NULL,
  `tb_consumo_frigobarcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_consumo_frigobar`, `id_quarto_fk`, `id_frigobar_fk`),
  INDEX `fk_tb_consumo_frigobar_tb_quarto_idx` (`id_quarto_fk` ASC),
  INDEX `fk_tb_consumo_frigobar_tb_frigobar1_idx` (`id_frigobar_fk` ASC),
  CONSTRAINT `fk_tb_consumo_frigobar_tb_quarto`
    FOREIGN KEY (`id_quarto_fk`)
    REFERENCES `hotelaria_db`.`tb_quarto` (`id_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_consumo_frigobar_tb_frigobar1`
    FOREIGN KEY (`id_frigobar_fk`)
    REFERENCES `hotelaria_db`.`tb_frigobar` (`id_frigobar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelaria_db`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelaria_db`.`tb_aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `id_cliente_fk` INT NOT NULL,
  `id_quarto_fk` INT NOT NULL,
  `aluguel_qtd_diarias` INT NULL,
  `aluguel_dt_ini_estadia` DATETIME NULL,
  `aluguel_dt_fim_estadia` DATETIME NULL,
  PRIMARY KEY (`id_aluguel`, `id_cliente_fk`, `id_quarto_fk`),
  INDEX `fk_tb_aluguel_tb_cliente1_idx` (`id_cliente_fk` ASC),
  INDEX `fk_tb_aluguel_tb_quarto1_idx` (`id_quarto_fk` ASC),
  CONSTRAINT `fk_tb_aluguel_tb_cliente1`
    FOREIGN KEY (`id_cliente_fk`)
    REFERENCES `hotelaria_db`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_quarto1`
    FOREIGN KEY (`id_quarto_fk`)
    REFERENCES `hotelaria_db`.`tb_quarto` (`id_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
